# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/asottile/pyupgrade
  rev: "v2.32.1"
  hooks:
  - id: pyupgrade
    args: ["--py38-plus"]

- repo: https://github.com/hadialqattan/pycln
  rev: "v1.3.2"
  hooks:
  - id: pycln
    args:
    - --all
    stages: [manual]

- repo: https://github.com/pre-commit/mirrors-isort
  rev: 'v5.10.1'
  hooks:
  - id: isort
    args:
    - --profile=black

- repo: https://github.com/psf/black
  rev: '22.3.0'
  hooks:
  - id: black
    args:
    - --skip-string-normalization

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.2.0'
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: double-quote-string-fixer

- repo: https://github.com/pycqa/flake8  # code
  rev: '4.0.1'
  hooks:
  - id: flake8
    name: flake 8 (src)
    args:
    - --max-line-length=88
    # D106 Missing docstring in public nested class
    # D401 First line should be in imperative mood
    - --extend-ignore=D106,D401
    additional_dependencies:
    - flake8-docstrings
    files: ^streamunolib/

- repo: https://github.com/pycqa/flake8  # tests
  rev: '4.0.1'
  hooks:
  - id: flake8
    name: flake 8 (tests)
    args:
    - --max-line-length=88
    # E501 Line too long
    - --extend-ignore=D, E501
    additional_dependencies:
    - flake8-docstrings
    files: ^tests/

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.950'
  hooks:
  - id: mypy
    additional_dependencies:
    - pytest-stub
    args:
    - --strict
